import type { Metadata } from "next";
import { Barriecito, Indie_Flower } from "next/font/google";
import "../styles/globals.css";

const barriecitoSans = Barriecito({
  variable: "--font-barriecito-sans",
  subsets: ["latin"],
  weight: ["400"],
});

const indieFlower = Indie_Flower({
  variable: "--font-indie-flower",
  subsets: ["latin"],
  weight: ["400"],
});

export const metadata: Metadata = {
  title: "Maze Multiplayer",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${barriecitoSans.variable} ${indieFlower.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
